CREATE TABLE ROOM(
ID NUMBER,
CONSTRAINT ROOM_ID PRIMARY KEY(ID),
PRODUCTNAME NVARCHAR2(50),
NUMBEROFGUESTS NUMBER,
PRICE NUMBER(5,2),
BREAKFASTINCLUDED NUMBER DEFAULT 0,
CONSTRAINT BREAKFASTINCLUDED_CHECK CHECK(BREAKFASTINCLUDED=0 OR BREAKFASTINCLUDED=1),
PETSALLOWED NUMBER DEFAULT 0,
CONTRAINT PETSALLOWED_CHECK CHECK(PETSALLOWED = 0 OR PETSALLOWED =1),
DATEAVAILABLEFROM TIMESTAMP,
HOTEL_ID NUMBER NOT NULL,
CONSTRAINT HOTELID_FK FOREIGN KEY(HOTEL_ID) REFERENCES HOTEL(ID)
)



SELECT *FROM ROOM

SELECT *FROM HOTEL

ALTER TABLE ROOM
DROP COLUMN HOTELID

ALTER TABLE ROOM
ADD HOTEL_ID NUMBER

ALTER TABLE ROOM
ADD CONSTRAINT HOTELID_FK FOREIGN KEY(HOTEL_ID) REFERENCES HOTEL(ID)